name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Code Style
      run: cargo fmt -- --check
    - name: Clippy
      run: RUSTFLAGS="-Dwarnings" cargo clippy --all
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        sudo apt update && sudo apt install -y gdb
        cargo test --verbose
